/** The real voice modules the gate measures, compiled from source. */
export {
	BERX_VOICE_ALL_LINES,
	BERX_VOICE_CHOSEN,
	BERX_VOICE_IDENTITY,
	BERX_VOICE_MIN_CONFIDENCE,
	BERX_VOICE_NAME_ASK,
	BERX_VOICE_NOT_HEARD,
	BERX_VOICE_OFFER,
	BERX_VOICE_PAUSE_AFTER_ANSWER,
	BERX_VOICE_PAUSE_AFTER_QUESTION,
	BERX_VOICE_PITCH,
	BERX_VOICE_RATE,
	BERX_VOICE_SILENT_PATH,
	BERX_VOICE_WAKING,
	BERX_ARRIVAL_ID,
	BERX_INTENT_OBJECT,
	BerxVoiceAssistant,
	BerxVoiceRegistration,
	berxApplyVoiceMoment,
	berxDetectTone,
	berxIntentFromSpeech,
	berxNameFromSpeech,
	berxNameInLight,
	berxRegistrationScene,
	berxVoiceAnswerTo,
	berxVoiceNameHeard,
	berxVoiceProsody,
	berxVoiceWelcome,
} from '@berx/spatial';
