/**
 * !!! VERIFICATION STATUS: UNVERIFIED — see BerxButton.tsx header.
 *
 * BERX GRAIN — the atmosphere layer.
 *
 * A gradient with no grain reads as CSS; the same gradient under a fine
 * monochrome noise reads as air, film or a lit surface. This is the
 * cheapest thing in the whole system that moves a screen from "app
 * background" to "photographed space", so it sits over every light
 * field.
 *
 * DEGRADATION IS DELIBERATE. The noise is generated by an SVG filter
 * (feTurbulence), and the rect it applies to has NO fill of its own —
 * so on any renderer that ignores the filter, this component paints
 * nothing at all rather than dropping an opaque plate over the screen.
 */
import {useMemo} from 'react';
import {View, StyleSheet, ViewStyle} from 'react-native';
import Svg, {Defs, Filter, FeTurbulence, FeColorMatrix, Rect} from 'react-native-svg';

export interface BerxGrainProps {
	/** 0..1. Above ~0.10 it stops being atmosphere and becomes texture. */
	opacity?: number;
	/** Higher = finer grain. */
	frequency?: number;
	style?: ViewStyle;
}

export function BerxGrain({opacity = 0.055, frequency = 0.9, style}: BerxGrainProps) {
	const uid = useMemo(() => Math.random().toString(36).slice(2, 8), []);
	return (
		<View pointerEvents="none" style={[StyleSheet.absoluteFillObject, {opacity}, style]}>
			<Svg width="100%" height="100%">
				<Defs>
					<Filter id={`${uid}-grain`} x="0" y="0" width="100%" height="100%">
						<FeTurbulence type="fractalNoise" baseFrequency={String(frequency)} numOctaves="3" stitchTiles="stitch" />
						{/* Drop the turbulence to luminance: coloured noise would tint
						    the ground and fight the light field's own colour. */}
						<FeColorMatrix
							type="matrix"
							values="0 0 0 0 0.5  0 0 0 0 0.5  0 0 0 0 0.5  0.4 0.4 0.4 0 0"
						/>
					</Filter>
				</Defs>
				<Rect x="0" y="0" width="100%" height="100%" fill="none" filter={`url(#${uid}-grain)`} />
			</Svg>
		</View>
	);
}
