/** BERX MAX 5D web GPU backend. Real WebGL2 perspective/depth renderer with spatial picking. */
import { pickSpatialObject, type Berx5DFrame, type BerxHit, type BerxVec3 } from '@berx/spatial';

type Mat4=Float32Array;
const VERTEX=`#version 300 es
precision highp float; layout(location=0) in vec3 aPosition; layout(location=1) in vec3 aNormal;
uniform mat4 uProjection; uniform mat4 uView; uniform mat4 uModel; out vec3 vNormal; out vec3 vWorld;
void main(){vec4 world=uModel*vec4(aPosition,1.0);vWorld=world.xyz;vNormal=mat3(uModel)*aNormal;gl_Position=uProjection*uView*world;}`;
const FRAGMENT=`#version 300 es
precision highp float; in vec3 vNormal; in vec3 vWorld; uniform vec3 uBase; uniform vec3 uEmissive; uniform float uEmissiveStrength; uniform float uMetalness; uniform float uRoughness; out vec4 outColor;
void main(){vec3 n=normalize(vNormal);vec3 key=normalize(vec3(.45,.72,.9));float ndl=max(dot(n,key),0.0);float spec=pow(max(dot(reflect(-key,n),normalize(-vWorld)),0.0),mix(64.0,8.0,uRoughness));vec3 lit=uBase*(.16+ndl*.72)+uBase*spec*(.12+uMetalness*.42)+uEmissive*uEmissiveStrength;outColor=vec4(lit,1.0);}`;
function perspective(f:number,a:number,n:number,far:number):Mat4{const q=1/Math.tan(f*Math.PI/360),nf=1/(n-far),m=new Float32Array(16);m[0]=q/a;m[5]=q;m[10]=(far+n)*nf;m[11]=-1;m[14]=2*far*n*nf;return m;}
function lookAt(p:BerxVec3,t:BerxVec3):Mat4{let z={x:p.x-t.x,y:p.y-t.y,z:p.z-t.z};let l=Math.hypot(z.x,z.y,z.z)||1;z={x:z.x/l,y:z.y/l,z:z.z/l};let x={x:z.y*0-z.z*1,y:z.z*0-z.x*0,z:z.x*1-z.y*0};l=Math.hypot(x.x,x.y,x.z)||1;x={x:x.x/l,y:x.y/l,z:x.z/l};const y={x:z.y*x.z-z.z*x.y,y:z.z*x.x-z.x*x.z,z:z.x*x.y-z.y*x.x},m=new Float32Array(16);m[0]=x.x;m[1]=y.x;m[2]=z.x;m[4]=x.y;m[5]=y.y;m[6]=z.y;m[8]=x.z;m[9]=y.z;m[10]=z.z;m[12]=-(x.x*p.x+x.y*p.y+x.z*p.z);m[13]=-(y.x*p.x+y.y*p.y+y.z*p.z);m[14]=-(z.x*p.x+z.y*p.y+z.z*p.z);m[15]=1;return m;}
function model(x:number,y:number,z:number,sx:number,sy:number,sz:number,rx:number,ry:number,rz:number):Mat4{const cx=Math.cos(rx),sxn=Math.sin(rx),cy=Math.cos(ry),syn=Math.sin(ry),cz=Math.cos(rz),szn=Math.sin(rz),m=new Float32Array(16);m[0]=cy*cz*sx;m[1]=cy*szn*sx;m[2]=-syn*sx;m[4]=(sxn*syn*cz-cx*szn)*sy;m[5]=(sxn*syn*szn+cx*cz)*sy;m[6]=sxn*cy*sy;m[8]=(cx*syn*cz+sxn*szn)*sz;m[9]=(cx*syn*szn-sxn*cz)*sz;m[10]=cx*cy*sz;m[12]=x;m[13]=y;m[14]=z;m[15]=1;return m;}
const CUBE=new Float32Array([-1,-1,1,0,0,1,1,-1,1,0,0,1,1,1,1,0,0,1,-1,1,1,0,0,1,-1,-1,-1,0,0,-1,-1,1,-1,0,0,-1,1,1,-1,0,0,-1,1,-1,-1,0,0,-1,-1,1,-1,0,1,0,-1,1,1,0,1,0,1,1,1,0,1,0,1,1,-1,0,1,0,-1,-1,-1,0,-1,0,1,-1,-1,0,-1,0,1,-1,1,0,-1,0,-1,-1,1,0,-1,0,1,-1,-1,1,0,0,0,1,1,-1,1,0,0,0,1,1,1,1,0,0,0,1,-1,-1,-1,-1,0,0,-1,-1,1,-1,0,0,-1,1,1,-1,0,0,-1,1,-1,-1,0,0]);
const INDICES=new Uint16Array([0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23]);
function compile(gl:WebGL2RenderingContext,type:number,src:string){const s=gl.createShader(type);if(!s)throw Error('BERX 5D shader allocation failed');gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const e=gl.getShaderInfoLog(s)||'shader error';gl.deleteShader(s);throw Error(e);}return s;}
function makeProgram(gl:WebGL2RenderingContext){const p=gl.createProgram();if(!p)throw Error('BERX 5D program allocation failed');gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,VERTEX));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,FRAGMENT));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)||'program link error');return p;}
const sub=(a:BerxVec3,b:BerxVec3):BerxVec3=>({x:a.x-b.x,y:a.y-b.y,z:a.z-b.z});
const norm=(v:BerxVec3):BerxVec3=>{const l=Math.hypot(v.x,v.y,v.z)||1;return{x:v.x/l,y:v.y/l,z:v.z/l};};
const cross=(a:BerxVec3,b:BerxVec3):BerxVec3=>({x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x});
export class BerxThreeRuntimeRenderer{
 private readonly gl:WebGL2RenderingContext;private readonly program:WebGLProgram;private readonly vao:WebGLVertexArrayObject;private readonly vbo:WebGLBuffer;private readonly index:WebGLBuffer;private width=1;private height=1;
 constructor(canvas:HTMLCanvasElement){const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,depth:true,powerPreference:'high-performance'});if(!gl)throw Error('BERX 5D requires WebGL2');this.gl=gl;this.program=makeProgram(gl);const vao=gl.createVertexArray(),vbo=gl.createBuffer(),ibo=gl.createBuffer();if(!vao||!vbo||!ibo)throw Error('BERX 5D GPU buffer allocation failed');this.vao=vao;this.vbo=vbo;this.index=ibo;gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,vbo);gl.bufferData(gl.ARRAY_BUFFER,CUBE,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ibo);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,INDICES,gl.STATIC_DRAW);gl.bindVertexArray(null);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);}
 resize(w:number,h:number){this.width=Math.max(1,w);this.height=Math.max(1,h);this.gl.viewport(0,0,this.width,this.height);}
 sync(frame:Berx5DFrame){const gl=this.gl;gl.useProgram(this.program);gl.bindVertexArray(this.vao);gl.clearColor(.027,.031,.039,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const c=frame.camera;gl.uniformMatrix4fv(gl.getUniformLocation(this.program,'uProjection'),false,perspective(c.fov,this.width/this.height,c.near,c.far));gl.uniformMatrix4fv(gl.getUniformLocation(this.program,'uView'),false,lookAt(c.position,c.target));for(const o of frame.world.objects){if(!o.visible)continue;gl.uniformMatrix4fv(gl.getUniformLocation(this.program,'uModel'),false,model(o.transform.position.x,o.transform.position.y,o.transform.position.z,o.transform.scale.x,o.transform.scale.y,o.transform.scale.z,o.transform.rotation.x,o.transform.rotation.y,o.transform.rotation.z));const premium=o.kind==='person'||o.kind==='moment';gl.uniform3f(gl.getUniformLocation(this.program,'uBase'),premium?.78:.18,premium?.77:.21,premium?.73:.24);gl.uniform3f(gl.getUniformLocation(this.program,'uEmissive'),.31,.84,.91);gl.uniform1f(gl.getUniformLocation(this.program,'uEmissiveStrength'),Math.min(1,o.energy)*.035);gl.uniform1f(gl.getUniformLocation(this.program,'uMetalness'),o.material.metalness);gl.uniform1f(gl.getUniformLocation(this.program,'uRoughness'),o.material.roughness);gl.drawElements(gl.TRIANGLES,INDICES.length,gl.UNSIGNED_SHORT,0);}gl.bindVertexArray(null);}
 pick(frame:Berx5DFrame,x:number,y:number):BerxHit|undefined{const c=frame.camera;const nx=(x/this.width)*2-1,ny=1-(y/this.height)*2;const forward=norm(sub(c.target,c.position)),right=norm(cross(forward,{x:0,y:1,z:0})),up=cross(right,forward),tan=Math.tan(c.fov*Math.PI/360),dir=norm({x:forward.x+right.x*nx*tan*(this.width/this.height)+up.x*ny*tan,y:forward.y+right.y*nx*tan*(this.width/this.height)+up.y*ny*tan,z:forward.z+right.z*nx*tan*(this.width/this.height)+up.z*ny*tan});return pickSpatialObject({origin:c.position,direction:dir},frame.world.objects);}
 render(frame:Berx5DFrame){this.sync(frame);}
 dispose(){const gl=this.gl;gl.deleteBuffer(this.vbo);gl.deleteBuffer(this.index);gl.deleteVertexArray(this.vao);gl.deleteProgram(this.program);}
}
